// Generated by https://quicktype.io

// =============== Backend Interfaces
export interface LoginResponse {
  usuario: Usuario;
  token: string;
}

export interface Usuario {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
  img?: string;
}

export interface LoginData {
  correo: string;
  password: string;
}

// =============== State Interfaces

export type Status = 'checking' | 'authenticated' | 'not-authenticated';

export interface AuthContextProps {
  errorMessage: string;
  token: string | null;
  user: Usuario | null;
  status: Status;
  signUp: () => void;
  signIn: (loginData: LoginData) => void;
  removeError: () => void;
  logOut: () => void;
}
export interface AuthState {
  status: Status;
  token: string | null;
  errorMessage: string;
  user: Usuario | null;
}

// =============== App Interfaces
export interface IChildrenAsProps {
  children: JSX.Element | JSX.Element[];
}
